export const books = [
  {
    id: 1,
    title: "To Kill a Mockingbird",
    genre: "Fiction",
    author: "Harper Lee",
    url: "https://m.media-amazon.com/images/P/0099549484.01._SCLZZZZZZZ_SX500_.jpg",
    category: "Currently Reading",
  },
  {
    id: 2,
    title: "1984",
    genre: "Science Fiction",
    author: "George Orwell",
    url: "https://m.media-amazon.com/images/I/41ThWzOJoRL.jpg",
    category: "Want to Read",
  },
  {
    id: 3,
    title: "The Great Gatsby",
    genre: "Fiction",
    author: "F. Scott Fitzgerald",
    url: "https://m.media-amazon.com/images/I/817+192hZyS.jpg",
    category: "Read",
  },
  {
    id: 4,
    title: "Pride and Prejudice",
    genre: "Romance",
    author: "Jane Austen",
    url: "https://m.media-amazon.com/images/I/51BnxMPowkL.jpg",
    category: "Currently Reading",
  },
  {
    id: 5,
    title: "The Hobbit",
    genre: "Fantasy",
    author: "J.R.R. Tolkien",
    url: "https://m.media-amazon.com/images/I/51rhKCx8EKL._SX326_BO1,204,203,200_.jpg",
    category: "Currently Reading",
  },
  {
    id: 6,
    title: "Brave New World",
    genre: "Science Fiction",
    author: "Aldous Huxley",
    url: "https://m.media-amazon.com/images/I/51GefY0QneL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    category: "Read",
  },
  {
    id: 7,
    title: "Harry Potter and the Sorcerer's Stone",
    genre: "Fantasy",
    author: "J.K. Rowling",
    url: "https://m.media-amazon.com/images/I/51P1Rfz5n3L._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    category: "Read",
  },
  {
    id: 8,
    title: "The Catcher in the Rye",
    genre: "Fiction",
    author: "J.D. Salinger",
    url: "https://m.media-amazon.com/images/I/418bOQWiRBL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    category: "Want to Read",
  },
  {
    id: 9,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    genre: "Fantasy",
    author: "J.R.R. Tolkien",
    url: "https://m.media-amazon.com/images/I/51myt0GXIUL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    category: "",
  },
  {
    id: 10,
    title: "To All the Boys I've Loved Before",
    genre: "Romance",
    author: "Jenny Han",
    url: "https://m.media-amazon.com/images/I/41Zdz7Om9YL._SX322_BO1,204,203,200_.jpg",
    category: "",
  },
];
